//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skizzel.Infrastructure.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Receipts = new HashSet<Receipt>();
            this.Millages = new HashSet<Millage>();
        }
    
        public int CategoryId { get; set; }
        public string Type { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Millage> Millages { get; set; }
    }
}
