//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skizzel.Infrastructure.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Receipts = new HashSet<Receipt>();
            this.Categories = new HashSet<Category>();
            this.Millages = new HashSet<Millage>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Millage> Millages { get; set; }
    }
}
